# Generated by Django 4.2.20 on 2025-07-01 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=15, unique=True)),
                ('estado', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'rd_usuarios',
            },
        ),
        migrations.CreateModel(
            name='estados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rd_estados',
            },
        ),
        migrations.CreateModel(
            name='etiologia',
            fields=[
                ('id_etiologia', models.AutoField(primary_key=True, serialize=False)),
                ('general', models.CharField(max_length=100)),
                ('especifica', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rd_etiologias',
            },
        ),
        migrations.CreateModel(
            name='fecha',
            fields=[
                ('id_fecha', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=100)),
                ('año', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
                ('dia', models.CharField(max_length=100)),
                ('mes_nombre', models.CharField(max_length=100)),
                ('fin_mes', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rd_fechas',
            },
        ),
        migrations.CreateModel(
            name='ipress',
            fields=[
                ('id_ipress', models.AutoField(primary_key=True, serialize=False)),
                ('ipress', models.CharField(max_length=15)),
                ('nombre_corto', models.CharField(max_length=50)),
                ('tipo_unidad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'rd_ipress',
            },
        ),
        migrations.CreateModel(
            name='modalidades',
            fields=[
                ('id_modalidad', models.AutoField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rd_modalidades',
            },
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('autogenerado', models.CharField(max_length=100)),
                ('paciente', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('grado_instruccion', models.CharField(max_length=100)),
                ('id_modalidad', models.ForeignKey(db_column='id_modalidad', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.modalidades')),
            ],
            options={
                'db_table': 'rd_pacientes',
            },
        ),
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('perfil', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'rd_perfiles',
            },
        ),
        migrations.CreateModel(
            name='periodos',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rd_periodos',
            },
        ),
        migrations.CreateModel(
            name='red',
            fields=[
                ('id_red', models.AutoField(primary_key=True, serialize=False)),
                ('red', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rd_redes',
            },
        ),
        migrations.CreateModel(
            name='tipoPacientes',
            fields=[
                ('id_tipo_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_paciente', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rd_tipo_pacientes',
            },
        ),
        migrations.CreateModel(
            name='ubigeo',
            fields=[
                ('id_ubigeo', models.AutoField(primary_key=True, serialize=False)),
                ('ubigeo_reniec', models.CharField(max_length=100)),
                ('ubigeo_inei', models.CharField(max_length=100)),
                ('codDepartamento_inei', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('codProvincia_inei', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rd_ubigeos',
            },
        ),
        migrations.CreateModel(
            name='usuarioIpress',
            fields=[
                ('id_usuario_ipress', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
                ('id_ipress', models.ForeignKey(db_column='id_ipress', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.ipress')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rd_usuarios_ipress',
                'unique_together': {('id_usuario', 'id_ipress')},
            },
        ),
        migrations.CreateModel(
            name='periodoIpress',
            fields=[
                ('id_periodo_ipress', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.estados')),
                ('id_ipress', models.ForeignKey(db_column='id_ipress', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.ipress')),
                ('id_periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.periodos')),
            ],
            options={
                'db_table': 'rd_periodos_ipress',
            },
        ),
        migrations.AddField(
            model_name='ipress',
            name='id_modalidad',
            field=models.ForeignKey(db_column='id_modalidad', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.modalidades'),
        ),
        migrations.AddField(
            model_name='ipress',
            name='id_red',
            field=models.ForeignKey(db_column='id_red', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.red'),
        ),
        migrations.AddField(
            model_name='ipress',
            name='id_ubigeo',
            field=models.ForeignKey(db_column='id_ubigeo', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.ubigeo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_perfil',
            field=models.ForeignKey(blank=True, db_column='id_perfil', null=True, on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='pacientesDialisis',
            fields=[
                ('id_paciente_dialisis', models.AutoField(primary_key=True, serialize=False)),
                ('modalidad_inicio_trr', models.CharField(max_length=20)),
                ('fecha_inicio_trr', models.CharField(max_length=100)),
                ('subsistema_salud', models.CharField(max_length=100)),
                ('tipo_acceso', models.CharField(max_length=100)),
                ('fecha_creacion_acceso', models.CharField(max_length=100)),
                ('fecha_primer_ingreso', models.CharField(max_length=100)),
                ('enf_ateroesclerotica_cardiaca', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_insuficiencia_cardiaca_congestiva', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_vascular_periferica', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_cerebro_vascular', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_cancer', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_diabetes', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_hipertension', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_tuberculosis', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_otra', models.CharField(blank=True, max_length=20, null=True)),
                ('id_etiologia', models.ForeignKey(db_column='id_etiologia', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.etiologia')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.pacientes')),
                ('id_periodo_ipress', models.ForeignKey(db_column='id_periodo_ipress', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.periodoipress')),
                ('id_usuario_ipress', models.ForeignKey(db_column='id_usuario_ipress', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.usuarioipress')),
            ],
            options={
                'db_table': 'rf_pacientes_dialisis',
                'unique_together': {('id_periodo_ipress', 'id_paciente', 'id_usuario_ipress')},
            },
        ),
    ]
