# Generated by Django 5.0.6 on 2025-09-07 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAsistencial', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='etiologia',
            fields=[
                ('id_etiologia', models.AutoField(primary_key=True, serialize=False)),
                ('general', models.CharField(max_length=100)),
                ('especifica', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rd_etiologias',
            },
        ),
        migrations.CreateModel(
            name='fecha',
            fields=[
                ('id_fecha', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=100)),
                ('año', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
                ('dia', models.CharField(max_length=100)),
                ('mes_nombre', models.CharField(max_length=100)),
                ('fin_mes', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rd_fechas',
            },
        ),
        migrations.CreateModel(
            name='modalidades',
            fields=[
                ('id_modalidad', models.AutoField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rd_modalidades',
            },
        ),
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('perfil', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'rd_perfiles',
            },
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rd_periodos',
            },
        ),
        migrations.CreateModel(
            name='red',
            fields=[
                ('id_red', models.AutoField(primary_key=True, serialize=False)),
                ('red', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rd_redes',
            },
        ),
        migrations.CreateModel(
            name='tipoPacientes',
            fields=[
                ('id_tipo_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_paciente', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rd_tipo_pacientes',
            },
        ),
        migrations.CreateModel(
            name='ubigeo',
            fields=[
                ('id_ubigeo', models.AutoField(primary_key=True, serialize=False)),
                ('ubigeo_reniec', models.CharField(max_length=100)),
                ('ubigeo_inei', models.CharField(max_length=100)),
                ('codDepartamento_inei', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('codProvincia_inei', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rd_ubigeos',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Ipress',
            fields=[
                ('id_ipress', models.AutoField(primary_key=True, serialize=False)),
                ('ipress', models.CharField(max_length=15)),
                ('nombre_corto', models.CharField(max_length=50)),
                ('tipo_unidad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=15)),
                ('id_modalidad', models.ForeignKey(db_column='id_modalidad', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.modalidades')),
                ('id_red', models.ForeignKey(db_column='id_red', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.red')),
                ('id_ubigeo', models.ForeignKey(db_column='id_ubigeo', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.ubigeo')),
            ],
            options={
                'db_table': 'rd_ipress',
            },
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('autogenerado', models.CharField(max_length=100)),
                ('paciente', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('grado_instruccion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('id_modalidad', models.ForeignKey(db_column='id_modalidad', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.modalidades')),
            ],
            options={
                'db_table': 'rd_pacientes',
            },
        ),
        migrations.CreateModel(
            name='pacientesDialisis',
            fields=[
                ('id_paciente_dialisis', models.AutoField(primary_key=True, serialize=False)),
                ('modalidad_inicio_trr', models.CharField(max_length=20)),
                ('fecha_inicio_trr', models.CharField(max_length=100)),
                ('subsistema_salud', models.CharField(max_length=100)),
                ('tipo_acceso', models.CharField(max_length=100)),
                ('fecha_creacion_acceso', models.CharField(max_length=100)),
                ('fecha_primer_ingreso', models.CharField(max_length=100)),
                ('enf_ateroesclerotica_cardiaca', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_insuficiencia_cardiaca_congestiva', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_vascular_periferica', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_cerebro_vascular', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_cancer', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_diabetes', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_hipertension', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_tuberculosis', models.CharField(blank=True, max_length=20, null=True)),
                ('enf_otra', models.CharField(blank=True, max_length=20, null=True)),
                ('id_periodo_ipress', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_ingreso_hospital', models.CharField(blank=True, max_length=20, null=True)),
                ('localizacion_acceso_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('hospital_procedencia_trr', models.CharField(blank=True, max_length=80, null=True)),
                ('etiologia', models.CharField(blank=True, max_length=20, null=True)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.pacientes')),
            ],
            options={
                'db_table': 'rf_pacientes_dialisis',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_perfil',
            field=models.ForeignKey(blank=True, db_column='id_perfil', null=True, on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.perfil'),
        ),
        migrations.CreateModel(
            name='periodoIpress',
            fields=[
                ('id_periodo_ipress', models.AutoField(primary_key=True, serialize=False)),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.estados')),
                ('ipress', models.ForeignKey(db_column='id_ipress', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.ipress')),
                ('periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.periodos')),
            ],
            options={
                'db_table': 'rd_periodos_ipress',
            },
        ),
        migrations.CreateModel(
            name='morbilidadesHospitalarias',
            fields=[
                ('diagnostico', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_diagnostico', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_hospitalizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_alta', models.CharField(blank=True, max_length=100, null=True)),
                ('fuente', models.CharField(blank=True, max_length=100, null=True)),
                ('id_morbilidad_hospitalaria', models.AutoField(primary_key=True, serialize=False)),
                ('filtroDescripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('seleccionados', models.CharField(blank=True, max_length=100, null=True)),
                ('fIniHos', models.CharField(blank=True, max_length=100, null=True)),
                ('fAltHos', models.CharField(blank=True, max_length=100, null=True)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.pacientes')),
                ('id_periodo_ipress', models.ForeignKey(db_column='id_periodo_ipress', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.periodoipress')),
            ],
            options={
                'db_table': 'rf_morbilidades_hospitalarias',
            },
        ),
        migrations.CreateModel(
            name='eventosAccesosVasculares',
            fields=[
                ('tipo_acceso_vascular', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio_antmicrobial', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio_vancomicina', models.CharField(blank=True, max_length=100, null=True)),
                ('hemocultivo_positivo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_acceso_vascular', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('fe_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('tpInfeccion', models.CharField(blank=True, max_length=100, null=True)),
                ('tratamientoIV', models.BooleanField(default=False)),
                ('vancomicinaIV', models.BooleanField(default=False)),
                ('hemocultivoPositivo', models.BooleanField(default=False)),
                ('tipoGram', models.CharField(blank=True, max_length=100, null=True)),
                ('tipoInfeccionLocal', models.CharField(blank=True, max_length=100, null=True)),
                ('tpGermen', models.CharField(blank=True, max_length=100, null=True)),
                ('bacteria', models.CharField(blank=True, max_length=100, null=True)),
                ('tipoBacteria', models.CharField(blank=True, max_length=100, null=True)),
                ('id_evento_acceso_vascular', models.AutoField(primary_key=True, serialize=False)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.pacientes')),
                ('id_periodo_ipress', models.ForeignKey(db_column='id_periodo_ipress', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.periodoipress')),
            ],
            options={
                'db_table': 'rf_eventos_accesos_vasculares',
            },
        ),
        migrations.CreateModel(
            name='PacienteRegistro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_created', models.DateTimeField(auto_now_add=True)),
                ('ipress', models.ForeignKey(db_column='id_ipress', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.ipress')),
                ('paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.pacientes')),
                ('periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.periodos')),
            ],
            options={
                'db_table': 'rf_paciente_registro',
            },
        ),
        migrations.CreateModel(
            name='resultadosClinicos',
            fields=[
                ('Hb', models.CharField(blank=True, max_length=100, null=True)),
                ('calcio', models.CharField(blank=True, max_length=100, null=True)),
                ('fosforo', models.CharField(blank=True, max_length=100, null=True)),
                ('PTHi', models.CharField(blank=True, max_length=100, null=True)),
                ('Alb', models.CharField(blank=True, max_length=100, null=True)),
                ('calcio_corregido', models.CharField(blank=True, max_length=100, null=True)),
                ('ktv', models.CharField(blank=True, max_length=100, null=True)),
                ('tiempo_dialisis', models.CharField(blank=True, max_length=100, null=True)),
                ('eritoproyetina', models.BooleanField(default=False)),
                ('hierro', models.CharField(blank=True, max_length=100, null=True)),
                ('hiperparatioidismo', models.BooleanField(default=False)),
                ('id_resultado_clinico', models.AutoField(primary_key=True, serialize=False)),
                ('tmpDialisis', models.CharField(blank=True, max_length=100, null=True)),
                ('eritropoyetina', models.CharField(blank=True, max_length=100, null=True)),
                ('hiperparatiroidismo', models.CharField(blank=True, max_length=100, null=True)),
                ('hb', models.CharField(blank=True, max_length=100, null=True)),
                ('pthi', models.CharField(blank=True, max_length=100, null=True)),
                ('alb', models.CharField(blank=True, max_length=100, null=True)),
                ('calcioCorregido', models.CharField(blank=True, max_length=100, null=True)),
                ('kt', models.CharField(blank=True, max_length=100, null=True)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.pacientes')),
                ('id_periodo_ipress', models.ForeignKey(db_column='id_periodo_ipress', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.periodoipress')),
            ],
            options={
                'db_table': 'rf_resultados_clinicos',
            },
        ),
        migrations.CreateModel(
            name='unidadesActuales',
            fields=[
                ('id_unidad_actual', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.CharField(blank=True, max_length=20, null=True)),
                ('VHB', models.CharField(blank=True, max_length=100, null=True)),
                ('VHC', models.CharField(blank=True, max_length=100, null=True)),
                ('VHI', models.CharField(blank=True, max_length=100, null=True)),
                ('AcHBs', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_acceso_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion_acceso_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('localizacion_acceso_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('cambio_acceso', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_cambio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion_acceso_nuevo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_acceso_nuevo', models.CharField(blank=True, max_length=100, null=True)),
                ('localizacion_acceso_nuevo', models.CharField(blank=True, max_length=100, null=True)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.pacientes')),
                ('id_periodo_ipress', models.ForeignKey(db_column='id_periodo_ipress', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.periodoipress')),
                ('id_red', models.ForeignKey(db_column='id_red', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.red')),
            ],
            options={
                'db_table': 'rf_unidades_actuales',
            },
        ),
        migrations.CreateModel(
            name='vacunaciones',
            fields=[
                ('turno', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('id_vacunacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.pacientes')),
                ('id_periodo_ipress', models.ForeignKey(db_column='id_periodo_ipress', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.periodoipress')),
                ('id_red', models.ForeignKey(db_column='id_red', on_delete=django.db.models.deletion.PROTECT, to='appAsistencial.red')),
            ],
            options={
                'db_table': 'rf_vacunaciones',
            },
        ),
        migrations.CreateModel(
            name='usuarioIpress',
            fields=[
                ('id_usuario_ipress', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
                ('id_ipress', models.ForeignKey(db_column='id_ipress', on_delete=django.db.models.deletion.CASCADE, to='appAsistencial.ipress')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rd_usuarios_ipress',
                'unique_together': {('id_usuario', 'id_ipress')},
            },
        ),
    ]
